name: eden_star
description: ''
# La ligne suivante empêche le package d'être accidentellement publié sur pub.dev en utilisant `flutter pub publish`. C'est préférable pour les packages privés.
publish_to: 'none' # Supprimez cette ligne si vous souhaitez publier sur pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.7
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  connectivity: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_native_splash: ^2.3.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/eden.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/eden.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/eden.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/eden.png"

flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/eden.png
    - assets/safid.png

